### ISSUE TITLE
No parser and no file path given, couldn't infer a parser

### ISSUE THREAD

**Issue by adriaanvanrossum** [creyD/prettier_action#1]
Getting this error when running a CI job:

```
> Run creyD/prettier_action@v1.0
/usr/bin/docker run --name ee6b...a3f0f --label 671ee6 --workdir /github/workspace --rm -e INPUT_COMMIT_MESSAGE -e INPUT_COMMIT_OPTIONS -e INPUT_FILE_PATTERN -e INPUT_PRETTIER_OPTIONS -e INPUT_BRANCH -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/queue/queue":"/github/workspace" 671ee6:b142...ead3  "Prettified Code!" "" "*" "" ""
Installing dependencies...
npm WARN saveError ENOENT: no such file or directory, open '/github/workspace/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/github/workspace/package.json'
npm WARN workspace No description
npm WARN workspace No repository field.
npm WARN workspace No README data
npm WARN workspace No license field.

up to date in 0.561s
found 0 vulnerabilities

/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin-prettier.js
+ prettier@1.19.1
added 1 package from 1 contributor in 0.404s
Prettifing files...
[error] No parser and no file path given, couldn't infer a parser.
##[error]Docker run failed with exit code 2
```

In the config I just use the defaults:

```yml
    steps:
      - name: Prettier Action
        uses: creyD/prettier_action@v1.0
```

**Comment by adriaanvanrossum** [comment]
Reading the docs is hard 😄

Fixed it by adding the required params:

```yml
- name: Prettier Action
  uses: creyD/prettier_action@v1.0
  with:
    prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
    branch: "${{ github.head_ref }}"
    file_pattern: "."
```
