### ISSUE TITLE
[BUG] `prettier` not installed correctly

### ISSUE THREAD

**Issue by kewbish** [creyD/prettier_action#113]
**What exactly happened?**

Our team is using this prettier action to format code on push to main. The action was working as of ~8h ago, but as of ~5h ago fails to install the `prettier` command correctly. No changes to our GitHub workflow were made and we've tried rerunning the workflow several times with the same result. We get:
```
Installing prettier...
Checking plugin: prettier-plugin-go-template
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found
```
on action run.

1. Go to Actions tab on a GitHub repository
2. Manually initiate an action using this action
3. Scroll down to job run (an example [here](https://github.com/ubccsss/ubccsss.org/actions/runs/4206994917/jobs/7305109667))

**What should've happened?**
The Action should have correctly installed `prettier`. 

**How did it look?**
Full stack trace:
```
Run creyD/prettier_action@v4.2
  with:
    prettier_options: --write **/*.+(js|html|css|json|md|yaml|yml)
    prettier_plugins: prettier-plugin-go-template
    github_token: ***
    only_changed: true
    commit_message: Prettified Code!
    same_commit: false
    file_pattern: *
    dry: false
    prettier_version: false
    working_directory: false
Run PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/runner/work/_actions/creyD/prettier_action/v4.[2](https://github.com/ubccsss/ubccsss.org/actions/runs/4206994917/jobs/7305175027#step:3:2)/entrypoint.sh
  PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/runner/work/_actions/creyD/prettier_action/v[4](https://github.com/ubccsss/ubccsss.org/actions/runs/4206994917/jobs/7305175027#step:3:4).2/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_COMMIT_MESSAGE: Prettified Code!
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: *
    INPUT_PRETTIER_OPTIONS: --write **/*.+(js|html|css|json|md|yaml|yml)
    INPUT_DRY: false
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: true
    INPUT_PRETTIER_PLUGINS: prettier-plugin-go-template
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
Installing prettier...
Checking plugin: prettier-plugin-go-template
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line [7](https://github.com/ubccsss/ubccsss.org/actions/runs/4206994917/jobs/7305175027#step:3:7)4: prettier: command not found
Problem running prettier with --write **/*.+(js|html|css|json|md|yaml|yml)
Error: Process completed with exit code 1.
```

**Where did you encounter the problem?**

- Repo: [ubccsss/ubccsss.org](https://github.com/ubccsss/ubccsss.org)
- Version v4.2

**Comment by shawnyu5** [comment]
Same here, workflows using this actions randomly started failing recently with the same error `/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found`

**Comment by infotexture** [comment]
Same here: https://github.com/dita-ot/docs/actions/runs/4211604746/jobs/7310061348

**Comment by WilliamsCJ** [comment]
Version 3.3 appears to be the latest version that is not affected.

**Comment by Piet2001** [comment]
Here the same issue in multile repo's.

**Comment by semseysandor** [comment]
A workaround for this bug: pin npm to version 8 in your job (if it's possible)
```
- name: Install npm v8
  run: npm i -g npm@8

- name: Check code-style
  uses: creyD/prettier_action@v4.2
  with:
    dry: true
    prettier_options: --check **/*.{md,yml}
```

**Comment by semseysandor** [comment]
I've done some debugging:

- it seems `prettier` is not found because `$PATH` is off:
    ```
    echo PATH=$PATH
    PATH=Unknown command: "bin"

    To see a list of supported npm commands, run:
      npm help:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    ```
- running `npm help` confirms `npm bin` is not available
    ```
    npm <command>

    Usage:

    npm install        install all the dependencies in your project
    npm install <foo>  add the <foo> dependency to your project
    npm test           run this project's tests
    npm run <foo>      run the script named <foo>
    npm <command> -h   quick help on <command>
    npm -l             display usage info for all commands
    npm help <term>    search for help on <term>
    npm help npm       more involved overview

    All commands:

        access, adduser, audit, bugs, cache, ci, completion,
        config, dedupe, deprecate, diff, dist-tag, docs, doctor,
        edit, exec, explain, explore, find-dupes, fund, get, help,
        hook, init, install, install-ci-test, install-test, link,
        ll, login, logout, ls, org, outdated, owner, pack, ping,
        pkg, prefix, profile, prune, publish, query, rebuild, repo,
        restart, root, run-script, search, set, shrinkwrap, star,
        stars, start, stop, team, test, token, uninstall, unpublish,
        unstar, update, version, view, whoami

    Specify configs in the ini-formatted file:
        /home/runner/.npmrc
    or on the command line via: npm <command> --key=value

    More configuration info: npm help config
    Configuration fields: npm help 7 config

    npm@9.3.1 /usr/local/lib/node_modules/npm
    ```
- check `npm` version
    ```
    npm version
    9.3.1
    ```
- In `npm v9` `npm bin` is removed: https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#%E2%9A%A0%EF%B8%8F-notable-breaking-changes
- `$PATH` is set by `npm bin` in https://github.com/creyD/prettier_action/blob/dc62bca389a680b8641b21787af5ab9beba97567/action.yml#L64

## Conclusion

It seems currently this action won't work with `npm v9`.
So I've executed `prettier` with `npm exec prettier` and it worked, step succeeded. I'm not sure if that's the way. In that case though `npm install` might be unneeded as according to the docs `npm exec` can fetch packages also.
But I'm not too much into Node and npm so I leave this decision for you :smiley:

**Comment by tgrothe** [comment]
> A workaround for this bug: pin npm to version 8 in your job (if it's possible)

The workaround you described works for me perfectly. Thanks for that. Here's my complete Workflow file:

```yml
name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Install npm v8
        run: npm i -g npm@8
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
```

I hope `prettier` will work with npm v9 in the future...
