### ISSUE TITLE
[BUG] Problem --writer

### ISSUE THREAD

**Issue by vt89** [creyD/prettier_action#115]
**What exactly happened?**
The following workflow gives this error:

```
Installing prettier...
Checking plugin: prettier-plugin-apex
Prettifying files...
Files:
/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found
Problem running prettier with --write
Error: Process completed with exit code 1.
```
Workflow:
```
name: Prettier Apex
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          only_changed: true
          prettier_plugins: "prettier-plugin-apex"
          prettier_options: --write
```

I have tried many times using different syntax for prettier_options but the issue is always the same.
