### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zethuman** [creyD/prettier_action#116]
**What exactly happened?**
Action is failed

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/51375666/227105407-3dc83d2e-e72e-4eea-8422-956e043a7170.png">

Configuration file:

```
      - name: Prettify markdown code
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check --write --prose-wrap always **/*.md
          clean_node_folder: false
```

**What should've happened?**
Success action complete

**Where did you encounter the problem?**

- Version creyD/prettier_action@v4.3
