### ISSUE TITLE
[BUG] Error: Process completed with exit code 1 when using prettier-php

### ISSUE THREAD

**Issue by rwrj** [creyD/prettier_action#124]
**What exactly happened?**
Getting this error when running the action: `Error: Process completed with exit code 1.`
This seems to be happening when initializing the prettier-php plugin

**What should've happened?**
Prettier should have run successfuly

**How did it look?**
Here is the full log from the run:-
```
Run creyD/prettier_action@v4.3
  with:
    prettier_options: --write **/*.{css,js,php} --print-width 120
    commit_message: Prettier Code Formatting
    prettier_plugins: @prettier/plugin-php
    same_commit: false
    file_pattern: *
    dry: false
    prettier_version: false
    working_directory: false
    only_changed: false
    github_token: ***
    clean_node_folder: true
Run PATH=$GITHUB_ACTION_PATH/node_modules/.bin:$PATH /home/runner/work/_actions/creyD/prettier_action/v4.3/entrypoint.sh
  PATH=$GITHUB_ACTION_PATH/node_modules/.bin:$PATH /home/runner/work/_actions/creyD/prettier_action/v4.3/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_COMMIT_MESSAGE: Prettier Code Formatting
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: *
    INPUT_PRETTIER_OPTIONS: --write **/*.{css,js,php} --print-width 120
    INPUT_DRY: false
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: false
    INPUT_PRETTIER_PLUGINS: @prettier/plugin-php
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
    INPUT_CLEAN_NODE_FOLDER: true
Installing prettier...
Checking plugin: @prettier/plugin-php
Error: Process completed with exit code 1.
```

**Where did you encounter the problem?**
When the action ran on making a push.

Here is my full configuration file for reference:-
```
name: Prettier Code Formatting

on:
  push:
    branches-ignore: [ live ]
#  pull_request:
#    branches-ignore: [ live ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: "--write **/*.{css,js,php} --print-width 120"
          commit_message: "Prettier Code Formatting"
          prettier_plugins: "@prettier/plugin-php"
          # only_changed: True
```

- Version [4.3]
