### ISSUE TITLE
[BUG] Dry run fails in spite of the fact that a line length does not exceed 80 chars.

### ISSUE THREAD

**Issue by piotrwalczak1** [creyD/prettier_action#130]
**What exactly happened?**

1. Run prettier action with dry run flag on the following example, prettier says it should be broken into new line, but when using prettier plugin in vscode with default settings and 80 line limit length (default), it formats to the first line, which should not be considered invalid by the action.

```
-    const queryResponse: QueryCommandOutput = await DynamodbClient.queryTable(
-      queryCommandInput,
-    );
+    const queryResponse: QueryCommandOutput =
+      await DynamodbClient.queryTable(queryCommandInput);
```

**What should've happened?**
```
const queryResponse: QueryCommandOutput = await DynamodbClient.queryTable(
```
This should be considered valid formatting. When formatting this in vscode with prettier plugin with 80 line length limit (default) it is considered valid and prettiefied. The line is 78 chars length and should not be considered invalid by the prettier action.

**How did it look?**
![image](https://github.com/creyD/prettier_action/assets/95431451/eda78ccc-b10d-4aa5-abbd-10cf2c0b39fb)

**Where did you encounter the problem?**

Github actions, version 4.3

**Comment by creyD** [comment]
If your config is correctly loaded into the action, then this seems to be a problem with prettier, not with the action, right? Otherwise please specify your config file, how you load the prettier config

**Comment by piotrwalczak1** [comment]
@creyD There is no config file specified, just the default prettier options.

```
      - name: Prettify code check (will fail if not conform to prettier code formatting standards)
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --write **/*.{ts,md,json,yml,yaml,js} --ignore-path .prettierignore
```          

I installed prettier locally and the issue is reproductible, when run prettier locally the situation I describe is reproducible - locally it formats well, but when I run your action - it is different.
