### ISSUE TITLE
What is status code 128?

### ISSUE THREAD

**Issue by adityaraute** [creyD/prettier_action#131]
I'm very new to this.
I don't understand what this action is doing in this particular execution.
What does a status code of 128 mean and why is the job failing? I cannot find any documentation either.

![image](https://github.com/creyD/prettier_action/assets/43912470/b4f8e743-6a6e-40a4-ae81-23696263e15c)

Please assist.

**Comment by creyD** [comment]
Please specify your yaml for using this action

**Comment by creyD** [comment]
Please try like this and see if the output changes: 
```

name: Prettier Action

on:
  push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
```
