### ISSUE TITLE
[FEATURE] Disable commits

### ISSUE THREAD

**Issue by f33r0** [creyD/prettier_action#138]
**What would you like to change about the program?**
Add feature for disabling commit

**Why do you think this is a cool idea?**
Hi, we're using another option for commits, because we needs sign commit, but pretifier commits when not asked, add a feature to disable this please

**Comment by nilsreichardt** [comment]
Use `prettier_options: --check .` is a workaround for that.

```yml
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # From https://github.com/creyD/prettier_action/tree/v4.3/?tab=readme-ov-file#example-2-using-the-only_changed-or-same_commit-option-on-pr
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
```
