### ISSUE TITLE
[BUG] prettier gets stuck on an infinite loop of reformatting

### ISSUE THREAD

**Issue by northwestwitch** [creyD/prettier_action#141]
Hello! 
We are reformatting markdown and yaml file using the action and it has been working great for years. (we are very happy with it, thank you! 🙏🏻 ) 
However, since yesterday we have started experiencing a strange behaviour: after the reformatting, the action keeps going on forever in an infinite loop that is broken only by pushing another commit to the branch:

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/1bd97033-875d-4dc9-8725-cfd76b13c637">

This is our workflow file:

```
name: Prettier

"on": [pull_request]

jobs:
    prettier:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        name: Prettier

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
                  persist-credentials: false

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write --no-error-on-unmatched-pattern --ignore-unknown --tab-width 4 **/*.md **/*.yml
                  only_changed: True
                  github_token: ${{ secrets.BUMPVERSION_TOKEN }}
```

Do you have any suggestion on how we could fix this problem? Could it be due to the new minor release of Prettier?

Many thanks in advance,
Chiara
