### ISSUE TITLE
getting error while using prettier action

### ISSUE THREAD

**Issue by iamrajiv** [creyD/prettier_action#18]
error link [https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=955632686](https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=955632686)

I have used below code in `prettier.yml`
```
name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{css,html,js,md}

```

**Comment by creyD** [comment]
The error log states that it fails during the checkout action, could you please try again with the latest version 2.3.1 of checkout and report if the error still occurs?

**Comment by iamrajiv** [comment]
@creyD btw this above code works fine when I have used to my personal repo i.e. [https://github.com/iamrajiv/test/pull/1](https://github.com/iamrajiv/test/pull/1) but when I implemented to other people repo i.e. [https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=955632686](https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=955632686) it is not working.

**Comment by iamrajiv** [comment]
> The error log states that it fails during the checkout action, could you please try again with the latest version 2.3.1 of checkout and report if the error still occurs?
@creyD when I used 2.3.1 shows this [https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=957687326](https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=957687326)

**Comment by creyD** [comment]
> @creyD btw this above code works fine when I have used to my personal repo i.e. [iamrajiv/test#1](https://github.com/iamrajiv/test/pull/1) but when I implemented to other people repo i.e. https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=955632686 it is not working.

This could have something to do with the SECRET_KEY I don't know how GitHub handles this. Could be that the owner of the repo doesn't have actions enabled or something?

**Comment by creyD** [comment]
> > The error log states that it fails during the checkout action, could you please try again with the latest version 2.3.1 of checkout and report if the error still occurs?
> 
> @creyD when I used 2.3.1 it shows this https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=957687326

That's because it's not prettier action which should be 2.3.1 but the checkout action! :)

**Comment by iamrajiv** [comment]
> > > The error log states that it fails during the checkout action, could you please try again with the latest version 2.3.1 of checkout and report if the error still occurs?
> > 
> > 
> > @creyD when I used 2.3.1 it shows this https://github.com/BITSoC/iBlog/pull/15/checks?check_run_id=957687326
> 
> That's because it's not prettier action which should be 2.3.1 but the checkout action! :)

you mean like this
```
name: Prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Action for Prettier
        uses: actions/checkout@v2.3.1
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v2.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{css,html,js,md}
```
