### ISSUE TITLE
You are not currently on a branch error on pull request push

### ISSUE THREAD

**Issue by adriaanvanrossum** [creyD/prettier_action#19]
With this config:

```yml
- name: Prettier Action on PR
  if: github.event_name == 'pull_request'
  uses: creyD/prettier_action@v3.0
  with:
    prettier_version: ^2.0.5
    prettier_options: "--write {,!(static|.github)/**/}*.{js,html,json,md,yml,css,scss} static/js/**/*.js"
    commit_message: "Run prettier via GitHub Action"
    branch: ${{ github.head_ref }}
    file_pattern: "."
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I get this error:

```
 file1.js 3ms
file2.js 42ms
Commiting and pushing changes...
[detached HEAD e646b5b] Run prettier via GitHub Action
 Author: *** <***>
 2 files changed, 108 insertions(+), 115 deletions(-)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```

I solved the issue by running prettier on my machine before pushing, but it should work of course.

Can you see what I'm doing wrong here?

**Comment by creyD** [comment]
With version 3 of the prettier action, we depreciated the branch parameter. Can you try without it real quick? It shouldn't change anything, but just to be safe?

**Comment by adriaanvanrossum** [comment]
You're quick! Just tested, same issue. Removing the branch option does not change anything.

**Comment by creyD** [comment]
As this probably is a problem with the checkout action, could you please share the config of that?

**Comment by adriaanvanrossum** [comment]
That config if very simple: 

```yml
- uses: actions/checkout@v2
```

**Comment by adriaanvanrossum** [comment]
That indeed solves the issue!

**Comment by creyD** [comment]
Very cool!

**Comment by koppor** [comment]
Same issue here. The solution does work if not on a pull request (the variable `github.head_ref` is only available at pulls - see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).

Workaround:

```yaml
      - name: Checkout source (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          show-progress: 'false'
      - name: Checkout source (no-PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
```

This does not solve the permission-denied issue, but might be better than nothing ^^.

     remote: Permission to koppor/jabref.git denied to github-actions[bot].

---

Not working workaround:

```yaml
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          show-progress: 'false'
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - run: git checkout ${{ steps.branch-name.outputs.current_branch }}
```

This fails, when PR comes from another repository
