### ISSUE TITLE
[Feature-Request] Should be able to check only changed files during CI. 

### ISSUE THREAD

**Issue by BiosBoy** [creyD/prettier_action#21]
**What exactly happened?**
Prettier Action checks all the codebase instead of the files which were changed only on the particular commit.

```
    - name: Prettier Action
      uses: creyD/prettier_action@v3.0
      with:
        prettier_version: 1.19.1
        prettier_options: --write **/*.{js,ts,tsx}
```

**What should've happened?**
Should be able to check only changed files during CI. 

**How did it look?**
Check the whole codebase instead. Why?

**Where did you encounter the problem?**
 - OS: ubuntu-latest
