### ISSUE TITLE
[FEATURE] Option to install Prettier plugins

### ISSUE THREAD

**Issue by infotexture** [creyD/prettier_action#22]
I'd like to use this action on repos that include XML files, and format them with [`@prettier/plugin-xml`](https://github.com/prettier/plugin-xml).

When I run the action as is, I get errors in the log:

```log
[warn] Ignored unknown option { xmlWhitespaceSensitivity: "strict" }. Did you mean htmlWhitespaceSensitivity?
Error:  No parser could be inferred for file: index.dita
```

This works fine when I run Prettier locally, as these options are provided by `plugin-xml`.

## Suggestion

💡 Add an option to that would allow users to specify the names of [Prettier plugins](https://prettier.io/docs/en/plugins.html) to install.

I realize it would be possible to fork this action and hard-code additional plugins into the [`# PROGRAM`](https://github.com/creyD/prettier_action/blob/master/entrypoint.sh#L28) section where Prettier itself is installed, but it seems like something that others might want to do too, so it might be best to support this here with an option instead.

**Comment by creyD** [comment]
Sounds cool, if you want you can create a PR for this!

**Comment by infotexture** [comment]
Parameterizing this might be beyond my ken, but I'll try to put something together and submit for your review.

**Comment by creyD** [comment]
Can you provide me with step by step instructions what needs to be done to achieve this?

**Comment by infotexture** [comment]
Prettier plug-ins are installed like Prettier itself, so where you do that on [Line 32 of entrypoint.sh](https://github.com/creyD/prettier_action/blob/master/entrypoint.sh#L32), you'd need to add the plug-ins to the list of things to install, like `plugin-xml`:

     npm install --silent --global prettier @prettier/plugin-xml

But I'm not sure whether you'd want to install all the [official plugins](https://prettier.io/docs/en/plugins.html#official-plugins), or how to best allow users to specify _which_ plugins they want to install. 🤔

**Comment by creyD** [comment]
I think it would be best to let users specify which plugins they want to install..

**Comment by stemount** [comment]
@creyD @infotexture for sure, checked out the PR.

It'd need to be something that ideally did a regex on another env variable such as...

```yaml
jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
                  # This is important to fetch the changes to the previous commit
                  fetch-depth: 0

            - name: Prettify code
              uses: creyD/prettier_action@v3.1
              with:
                  # We only check ONLY_CHANGED as this is a PR action
                  plugins:
                      - plugin-xml
```
