### ISSUE TITLE
Allow to work on pull_request and master branch

### ISSUE THREAD

**Issue by adriaanvanrossum** [creyD/prettier_action#3]
Not sure if this is possible, but it would be nice to have only one step instead of these two:

```yml
- name: Prettier Action on PR
  if: github.event_name == 'pull_request'
  uses: creyD/prettier_action@v1.0
  with:
    prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
    branch: ${{ github.head_ref }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Prettier Action on master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  uses: creyD/prettier_action@v1.0
  with:
    prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
    branch: master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Somehow it would be nice to not have to specify a branch. That is automatically would know if it's a PR or if it's just a push. If it's not available in your app than we could do something like this:

```yml
- name: Prettier Action
  uses: creyD/prettier_action@v1.0
  with:
    prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    event_name: ${{ github.event_name }}
    ref: ${{ github.ref }}
```

**Comment by creyD** [comment]
This isn't really possible because -as for the `GITHUB_TOKEN`-, my repository and therefore the Action can't access the issuing (your) repository. Even if you provide the event name, my action doesn't know where to push to. If you just only want to merge to the origin branch, then this should do the job -the on parameter is [documented here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on):

```yaml
on: [push, pull_request]
- name: Prettier Action on master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  uses: creyD/prettier_action@v1.0
  with:
    prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
    branch: ${{ github.ref }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The branch SHOULD be filled with master automatically if it's the on push event.

**Comment by adriaanvanrossum** [comment]
I'm already using the `on` parameter like this:

```yml
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
```

Which works great.

I think I'm not clear on what I would love to have. I would love that the GitHub Action would work without specifying the branch. Or where it would work for both a _PR_ and for a normal _push_.

Maybe this works?

```yml
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Prettier Action on master
        uses: creyD/prettier_action@v1.0
        with:
          prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
          branch: ${{ github.head_ref || github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Note the _branch_ name (`${{ github.head_ref || github.ref }}`).
