### ISSUE TITLE
[FEATURE] Use repo prettier configuration.

### ISSUE THREAD

**Issue by Ayfri** [creyD/prettier_action#41]
**What would you like to change about the program?**
I would like to be able to use the repo prettier configuration, instead of putting it into the action configuration, if it is already possible, how can I do it?

**Why do you think this is a cool idea?**
Automate more the usage of this action.

**Comment by creyD** [comment]
That would be a good idea! We don't have this in place yet, I always do it via the `prettier_options` parameter. But we could integrate this.

**Comment by creyD** [comment]
This is also doable via the `prettier_options` using your path `--config app/.prettierrc`.

**Comment by fschoenfeldt** [comment]
@creyD I don't want to hijack this request but I'm having a similar question regarding the use of the `.prettierignore` file. How do I pass it to the action? [The ` --ignore-path "./.prettierignore"` parameter](https://prettier.io/docs/en/cli.html#--ignore-path) doesn't seem to work because the action throws the following errors:

```bash
Error:  No parser could be inferred for file: x/y/assets/splash@1.5x.png
Error:  No parser could be inferred for file: x/y/assets/splash@2x.png
Error:  No parser could be inferred for file: x/y/assets/splash@3x.png
Error:  No parser could be inferred for file: x/y/assets/splash@4x.png
```

My prettierignore looks like this:
```
(...)
x/y/*.png
(...)
```

Workflow yaml:

```yaml
      - name: Check Code Formatting
        uses: creyD/prettier_action@v3.3
        with:
          # only_changed: true
          dry: true
          prettier_options: --write x/y/**/* --ignore-path "./.prettierignore"
```

As a workaround, I'll just add the filetypes to the `--write` parameter.
