### ISSUE TITLE
[BUG] Unexpected input(s) 'prettier_plugins' or Syntax Error

### ISSUE THREAD

**Issue by NanoCode012** [creyD/prettier_action#47]
**What exactly happened?**
1. Create a yml following the ReadMe
2. Add prettier_plugins like the below
3. Get warning/error below

```
Warning: Unexpected input(s) 'prettier_plugins', valid inputs are ['entryPoint', 'args', 'commit_message', 'same_commit', 'commit_options', 'file_pattern', 'prettier_options', 'dry', 'prettier_version', 'only_changed']
```

```yaml
name: Continuous Integration

# This action works with pull requests
on:
  pull_request:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_plugins: "@prettier/plugin-php"
        prettier_options: --write **/*.{php,css,js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**What should've happened?**
No error. Would like to use the official prettier/prettier-php plugin.

**How did it look?**
![image](https://user-images.githubusercontent.com/9899957/114212796-6d1cb080-998c-11eb-8131-4bf2f1cfc95e.png)

**Where did you encounter the problem?**
Using Github Actions 

**Additional info**
I understand that I should not encapsulate it in quotes, but I get another error below.
![image](https://user-images.githubusercontent.com/9899957/114214301-55462c00-998e-11eb-8252-c6baad7b7368.png)
