### ISSUE TITLE
[BUG] When doing dry run it still marks the job as DONE (green blob) even if there are ugly files in the repo

### ISSUE THREAD

**Issue by Niedzwiedzw** [creyD/prettier_action#52]
```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Check code style
      uses: creyD/prettier_action@v3.3
      with:
        # This part is also where you can pass other options, for example:
        dry: true
        prettier_options: "-c src/**/*.{ts,vue}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
despite warnings being printed the job doesn't fail
