### ISSUE TITLE
[BUG] Checking all files when using `only_changed` and `dry`

### ISSUE THREAD

**Issue by olaven** [creyD/prettier_action#61]
Hi! Thank you for maintaining this action :-)
I'm unfortunaltely experiencing what I believe is unexpected behaviour when using the config below.

**What exactly happened?**
Fails even though all files in changed in the latest commit are formatted properly. 

1. add code to a file, and format it according to the `.prettierrc`
2. use the following github job: 
```yml
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          dry: True
          only_changed: True
          prettier_options: --write **/*.{ts,js} --config ./.prettierrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**What should've happened?**
I expected the job to pass. Other files in the repository are 
not properly formatted, but I expected those to be ignored due to `only_changed: True`. 

I'm using v3.3.

**Comment by tam-carre** [comment]
I'm experiencing the same issue with v4.0. @olaven what about you?

**Comment by andycookfr** [comment]
I'm still getting this too.

```
    INPUT_COMMIT_MESSAGE: Prettified Code!
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: *
    INPUT_PRETTIER_OPTIONS: --check **/*.{js,jsx,less}
    INPUT_DRY: true
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: true
    INPUT_PRETTIER_PLUGINS: 
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
```

The output suggests that there are no matching files (as I'd expect; my PR has no js/jsx/less changes):
```
Installing prettier...
Prettifying files...
Files:
Checking formatting...
...
```

But then goes on to run all files in the repo anyway and fails.
