### ISSUE TITLE
package-lock.json getting deleted

### ISSUE THREAD

**Issue by johannbotha** [creyD/prettier_action#64]
I'm noticing that this prettier action is deleting my `package-lock.json` file. (Note that runny prettier via npx doesn't do this)

My action.yml
```
name: Do Prettier
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write .
```
my `.prettierrc.json`
```
{
  "singleQuote": true,
  "printWidth": 120
}
```

my `.prettierignore`
```
package-lock.json
*.html
*.min.js
```

[Example commit](https://github.com/johannbotha/test-pretty/commit/8e63d2e12fc55c2ab8f56faa15ab1cf3f48ed9d8)  where `package-lock.json` gets removed

**Comment by johannbotha** [comment]
Essentially this is deleting the `package-lock.json` and then committing those changes.

```
if [ -f 'package-lock.json' ]; then
  git reset --hard package-lock.json || rm package-lock.json
```

**Comment by johannbotha** [comment]
I ended up just doing something like this
```
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
  - run: npm i
  - run: npx prettier --check .
```
