### ISSUE TITLE
[BUG] entrypoint.sh: line 123: syntax error near unexpected token `then'

### ISSUE THREAD

**Issue by lambda-science** [creyD/prettier_action#79]
**What exactly happened?**
Workflow with Prettier failing:
https://github.com/lambda-science/EHRoes/runs/4475783348?check_suite_focus=true
```yaml
name: Format Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --check"

      - name: Prettify code
        uses: creyD/prettier_action@v4.1
        with:
          prettier_options: --check **/*.{css,js}
          only_changed: True
```
**What should've happened?**
Should pass as there is not error.

**Where did you encounter the problem?**
 - OS: Linux WSL2 20.04
- Repo: [https://github.com/lambda-science/EHRoes/tree/dev](https://github.com/lambda-science/EHRoes/tree/dev)
