### ISSUE TITLE
[BUG] How to run only in a specific directory of a project?

### ISSUE THREAD

**Issue by mfn** [creyD/prettier_action#90]
**What exactly happened?**
I used the action like this:
```yaml
      - name: prettier check
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_version: ${{ env.PRETTIER_VERSION }}
          prettier_options: --no-editorconfig --check src/ internals/
          working_directory: subdir/
```
This didn't work and I get:
> `/home/ubuntu/actions-runner/_work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 44: cd: subdir/: No such file or directory`

I thought maybe I need to provide the workspace, tried with:
```yaml
          working_directory: ${{ github.workspace }}/subdir/
```
But that gave only:
```
Installing prettier...
Error: Process completed with exit code 1.
```
No further details 🤷🏼 

I then had to resorted to this:
```
      - name: prettier check
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_version: ${{ env.PRETTIER_VERSION }}
          prettier_options: --no-editorconfig --check --ignore-path subdir/.prettierignore subdir/src/ subdir/internals/
```
I'd have hoped that using a working_directory it would auto-pick up the .prettierignore from there etc.

But at this point, I've no idea how `working_directory` works and have the impression it's used for something else.

Is it possible to install prettier and point it to a specific directory and "work from there"?

thank you 🙏🏼
