### ISSUE TITLE
[BUG] 4.2 fails with no such file or directory

### ISSUE THREAD

**Issue by markstos** [creyD/prettier_action#91]
**What exactly happened?**

```
 - name: Run prettier on changed files
   uses: creyD/prettier_action@v4.2
        with:
          only_changed: True
          dry: True
          prettier_options: --config ./api/.prettierrc --ignore-path ./api/.prettierignore --check ./api/src/**
```

**What should've happened?**

It should have succeeded or failed with a clear error message.
**How did it look?**

```
Run PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/github/action-runner/_work/_actions/creyD/prettier_action/v4.2/entrypoint.sh
  PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/github/action-runner/_work/_actions/creyD/prettier_action/v4.2/entrypoint.sh
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_COMMIT_MESSAGE: Prettified Code!
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: *
    INPUT_PRETTIER_OPTIONS: --config ./api/.prettierrc --ignore-path ./api/.prettierignore --check ./api/src/**
    INPUT_DRY: true
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: true
    INPUT_PRETTIER_PLUGINS: 
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
npm info it worked if it ends with ok
npm info using npm@6.14.15
npm info using node@v12.22.6
npm timing npm Completed in 48ms
npm info ok 
/__w/_temp/cda1fe4d-556f-48b7-b555-744d14a51b4d.sh: line 1: /home/github/action-runner/_work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: No such file or directory
Error: Process completed with exit code 127.
```

**Where did you encounter the problem?**

- Version: 4.2
