### ISSUE TITLE
[BUG] working_directory alway return the path is not a file or dir

### ISSUE THREAD

**Issue by Fatpandac** [creyD/prettier_action#94]
how to use working_directory ?
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/30423976/177777555-4d35c9e6-4843-4825-823b-888dc893cbf4.png">

**Comment by creyD** [comment]
Can you please add your config and if the repo is public a link to the repo?

**Comment by Fatpandac** [comment]
```
name: auto prettier

on:
  push:
    branches:
      - feat/refactor_docs_site
    paths:
      - 'site-vuepress/**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          working_directory: 'site-vuepress/'
          same_commit: true
          prettier_options: --write .
```

repo link: https://github.com/Fatpandac/arthas

**Comment by ParthS007** [comment]
<img width="1134" alt="Screenshot 2022-07-28 at 09 16 53" src="https://user-images.githubusercontent.com/24358501/181444509-80923586-9162-46bb-aed5-c0e79cd6af38.png">

@creyD Same is happening , did you had the time to look into this?

Some info that might help:

I have another workflow where I use the `working-directory` variable and it works fine with `./ui` directory. Maybe some where in the [code](https://github.com/creyD/prettier_action/blob/master/entrypoint.sh#L40-L46) where you parse the arg to `working-directory`. Thanks for your time.

<img width="993" alt="Screenshot 2022-07-28 at 09 19 04" src="https://user-images.githubusercontent.com/24358501/181444924-8d75e2a4-1ad0-47d8-bf72-07ae4654207f.png">



@Fatpandac Do you have a workaround for this already?

**Comment by creyD** [comment]
Really sorry, I didn't find the time yet. Could you test please without the ''? So this would be `working_directory: site-vuepress/`?

**Comment by Fatpandac** [comment]
Thank you so much for your reply to me again. 
I do not need to work out this problem now.
You can help @ParthS007 to work out this problem.

**Comment by creyD** [comment]
@ParthS007 Could you please post your repo or the action config here?

**Comment by ParthS007** [comment]
Sure, Here's the workflow file: https://github.com/ParthS007/analysispreservation.cern.ch/blob/master/.github/workflows/ui-test.yml

and this is the latest workflow run: https://github.com/ParthS007/analysispreservation.cern.ch/runs/7575015767?check_suite_focus=true

Thanks for your time.

**Comment by ParthS007** [comment]
@creyD Any updates on this bug if you had the time to look into the issue. Thanks

**Comment by creyD** [comment]
Can you try with `working-status: ui/`?

**Comment by ParthS007** [comment]
Thanks, The error is not there anymore but I see this [warning](https://github.com/ParthS007/analysispreservation.cern.ch/runs/7608358568?check_suite_focus=true#step:3:1):

```
Warning: Unexpected input(s) 'working-status', valid inputs are ['commit_message', 'commit_description', 'same_commit', 'commit_options', 'push_options', 'file_pattern', 'prettier_options', 'dry', 'prettier_version', 'working_directory', 'only_changed', 'prettier_plugins', 'github_token']
```

This is the workflow [file](https://github.com/ParthS007/analysispreservation.cern.ch/blob/prettier/.github/workflows/ui-test.yml). 

Although, I see now `only_changed` is not taken in consideration. I want to run this action only on changed files in the commit, It checks all code in the [`ui/`](https://github.com/ParthS007/analysispreservation.cern.ch/runs/7608358568?check_suite_focus=true#step:3:35). Is this related or something not possible?

**Comment by totoprayogo1916** [comment]
still waiting for fix this issue 🙄

**Comment by lnxd** [comment]
It looks like the working directory value requires absolute paths. In my case I was able to track down the path my code was checked out to.

It's very likely that anyone who wants to troubleshoot this needs to enter the `working_directory` path in the format:
`/home/runner/work/repo-name/repo-name/working-directory-name`.

Regardless, this only got me to another dead end:
`/home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh: line 74: prettier: command not found`

I'm thinking possible solutions to this would be to ensure prettier is in $PATH, `working_directory` possibly could be added to the prettier command instead of `cd`ing to the directory, or the `entrypoint.sh` might need to be updated to use an `./absolute/path/to/prettier` instead.

**Comment by creyD** [comment]
Thanks for the comment, sorry I didn't see it earlier. The working_directory option changes before prettier command is installed and sets the directory for the entire action. So yes, prettier is installed at the path you specify. That being said prettier_options can -like you showed- be used to specify directory as well. So it should actually work in my opinion.

@ParthS007 If you are still up to it (after such a long time) we should tackle this once and for all. I believe my autocorrect messed up when I wrote `working-status`, I meant `working_directory`. But I think you already tested it, right?

**Comment by jvansan** [comment]
Thanks for the work-around notes @lnxd. I just wanted to add for anyone who tries to run these checks using the [`act`](https://github.com/nektos/act) CLI to test actions locally, I ran into an issue where I received an error running this in a git worktree (not sure if this would also happen without the worktree).

```
[Run Code Quality/code-quality]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3-composite-0.sh] user= workdir=
| Installing prettier...
| Prettifying files...
| Files:
| Checking formatting...
| All matched files use Prettier code style!
| Prettier result: 0
| Deleting node_modules/ folder...
| fatal: not a git repository: /Users/jvansan/Code/unpdash/.git/worktrees/unpdash-code-review
```

This error does not occur in a GitHub action runner though so just a point of information.

**Comment by neilime** [comment]
Working directry seams useless for prettier installation as well. Of course it installs prettier in the expected working directory but when running npx, prettier is not found so it is installed globally again:

```yml
    - uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
      with:
        prettier_options: --write ${{ steps.prepare-variables.outputs.working-directory }}/**/*.md ${{ steps.prepare-variables.outputs.values-file }}
        working_directory: test/
```

```txt
Run creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0
Installing prettier...
Prettifying files...
Files:
npm warn exec The following package was not found and will be installed: prettier@3.6.2
```

Same problem when using `clean_node_folder`, the node_module folder is not found so not cleaned:

```yml
    - uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
      with:
        prettier_options: --write ${{ steps.prepare-variables.outputs.working-directory }}/**/*.md ${{ steps.prepare-variables.outputs.values-file }}
        working_directory: test/
        clean_node_folder: true
```

```txt
Deleting node_modules/ folder...
No node_modules/ folder.
```
