### ISSUE TITLE
[BUG] Not able to recognize parser when running prettier_version by default on latest version

### ISSUE THREAD

**Issue by nereagit** [creyD/prettier_action#97]
When running the action on Prettier's latest version with `prettier_version = false` the following error is thrown:

`Error:  No parser and no file path given, couldn't infer a parser.`

At the time this issue is open, the latest version is `2.5.1.`

The configuration in the YML file is the following,

```
name: Execute Prettier Check
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          only_changed: true
          prettier_options: --check
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
